### ISSUE TITLE
Bose Binding not show in Paper UI

### ISSUE THREAD

**Issue by supoeric** [marvkis/org.openhab.binding.bosesoundtouch-dist#2]
Bose Binding not show in Paper UI after upgrade openhab2 to 2.3.0 Build #1244.

**Comment by marvkis** [comment]
Hi,

I just uploaded an new jar file: https://github.com/marvkis/org.openhab.binding.bosesoundtouch-dist/raw/master/org.openhab.binding.bosesoundtouch-2.3.0-SNAPSHOT.jar - this version is working on my 2.3.0 Build #1232 - hope it still works on #1244.
There is a known issue with resolving all dependencies properly - see comment on #1 - you might need to do a
```
feature:install openhab-httpclient
```
to have all dependencies installed properly.
Hope this helps.
Cheers

**Comment by supoeric** [comment]
Hi,
Thanks
it work, I confirm it work on latest openHAB 2.3.0 Build #1249.
Will you continue to add the feature or improve the binding?
I'm using soundtouch 300.

Best Regards
Supoeric

**Comment by marvkis** [comment]
Hi Supeoeric,

Thanks you for the feedback.

Yes, it will continue. Currently it seems the plugin might get integrated into eclipse-smarthome itself ;)
See details in https://github.com/openhab/openhab2-addons/pull/2233
Do you have any special feature in mind?

Cheers,
   Chris
(I'm closing the issue as it works with the new version. Did you need to install the 'openhab-httpclient' feature or did it resolve automatically?)

**Comment by supoeric** [comment]
I install the 'openhab-httpclient' feature to resolve it.
